export const styles = {
    container: 'w-full my-5',
    tabContainer: 'flex border-b border-gray-300 mb-5 relative w-full',
    tabList: 'flex flex-1 w-full overflow-hidden',
    tab: 'flex-1 px-5 py-2.5 cursor-pointer bg-gray-50 border border-gray-300 border-b-0 rounded-t-lg text-center whitespace-nowrap overflow-hidden text-ellipsis min-w-0 flex items-center justify-center',
    tabText: 'overflow-hidden text-ellipsis whitespace-nowrap max-w-full',
    lastTab: 'mr-0',
    activeTab: 'bg-white border-b border-white -mb-px',
    moreButton: 'px-5 py-2.5 cursor-pointer bg-gray-50 border border-gray-300 border-b-0 rounded-t-lg relative min-w-[100px] flex items-center justify-center',
    dropdown: 'absolute top-full right-0 bg-white border border-gray-300 rounded-lg shadow-lg z-10 max-h-[300px] overflow-y-auto min-w-[200px]',
    dropdownItem: 'px-5 py-2.5 cursor-pointer border-b border-gray-200 hover:bg-gray-50',
    treeContainer: 'border border-gray-300 rounded-lg p-5 mx-5 box-border bg-white',
    treeNode: 'w-full box-border border border-gray-300 rounded-lg p-1.5 my-1.5',
    label: 'font-semibold',
    nodeContent: 'pl-5',
    nodeRow: 'flex items-center p-2 rounded-lg transition-colors',
    toggleButton: 'w-5 h-5 mr-2 flex items-center justify-center cursor-pointer border-none bg-transparent text-gray-600',
    keyName: 'font-bold mr-2',
    valueText: 'text-gray-700 w-full',
    activeDropdownItem: 'bg-gray-100',
    codeBlock: 'bg-gray-50 border border-gray-300 rounded-lg p-2.5 whitespace-pre-wrap font-mono text-sm w-full',
    codePre: 'w-full max-h-[500px] overflow-scroll text-black',
    image: 'max-w-full max-h-[500px] h-auto m-2.5',
    loadingSpinner: 'flex justify-center items-center h-[100px]',
    redColor: 'bg-red-500 border-red-500',
    textLabel: 'text-black w-[90%] inline-block',
    buttonLabel: 'p-1.5 border border-gray-600 rounded-lg mx-2.5 inline-block whitespace-nowrap text-white font-normal',
    linkLabel: 'text-blue-800 font-extrabold',
    nodeLabel: 'text-gray-600 text-sm font-thin',
};